#pragma once

enum class ConnectionState {
    CLIENT_READING_HEADERS,
    CLIENT_READING_BODY,

    BACKEND_CONNECTING,
    BACKEND_WRITING_REQUEST,
    BACKEND_READING_RESPONSE,

    CLIENT_WRITING_RESPONSE,

    CLOSED
};
